Fix missing sentinel warning
ucurihandler.cpp: In constructor 'UCUriHandler::UCUriHandler()':
ucurihandler.cpp:78:73: error: missing sentinel in function call [-Werror=format=]
   78 |     char* path = nih_dbus_path(NULL, , applicationId.constData(), NULL);
      |                                                                         ^